# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        BackendBundle\Entity\User:
            algorithm: bcrypt
            cost: 4 
            # sifrar la contraseña

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:       #autenticaciom de login
        user_db_provider: #provider de usuario
            entity:  
                class: BackendBundle:User #de la clase Usuario
                property: email #propiedad que autentica al usuario

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: /login  
                check_path: /login_check #comprueva si el usuario existe
            logout:
                path: logout
                target: / #cuando sale de la sesion  
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
