following_follow:
    path: /follow
    defaults: { _controller: AppBundle:Following:follow }
    methods: [POST] #solo permitira que se pueda accerder a la ruta con metodo POST

following_unfollow:
    path: /unfollow
    defaults: { _controller: AppBundle:Following:unfollow }
    methods: [POST] #solo permitira que se pueda accerder a la ruta con metodo POST

